# Generated by Django 4.2.30 on 2026-05-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_thumbnail_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
